sudo: false
language: node_js

node_js:
  - "0.12"
  - iojs
  - "4"
  - "6"
  - "stable"
  
install: "npm i -g yarn && yarn"

script: "npm run travis"

after_success:
  - npm run test:coveralls
  - rm -rf ./coverage
